#!/usr/bin/env bash
#
# An attemp to make a unified interface for different 
# package managers, including pacman, apt, dnf, xbps
#
# TODO: pkg.conf
# TODO: use file descriptor (fd) for reading different distro files
# TODO: set the package manager backend (and distro) only once
#

CURDIR="$(dirname $0)"
INCDIR="$CURDIR/include"

function usage() {
    echo "usage"
}

function package_manager() {
    file="/etc/os-release"
    [ -f $file ] && distro=$(cat $file | grep -w "ID" | cut -d '=' -f 2) || distro="None"

    [ "$distro" = "manjaro" ] && echo "pacman"

}

function source_file() {
    PKGMGR="$(package_manager)"

    [ "$PKGMGR" = "pacman" ] && source "$INCDIR/pacman.sh"
}


function main() {
    # source the relevant backend commands
    source_file

    case "$1" in
         "update" | "")
            update_mirrors
            ;;
        "upgrade")
            upgrade_system
            ;;
        "query")
            query_package
            ;;
        "make")
            make_package
            ;;
        "remove")
            remove_package
            ;;
        "purge")
            purge_package
            ;;
        *)
            usage
            ;;
    esac
}

main $@



